version: 0.2
run-as: root
phases:

  install:
    commands:
      - pwd
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
      - chmod +x eks_cicd/prereqs.sh
      - sh eks_cicd/prereqs.sh
  pre_build:
    commands:
      - aws sts get-caller-identity
      - echo Logging in to Amazon EKS...
      - aws eks update-kubeconfig --name k8scluster --region ap-northeast-1 
      - kubectl config view --minify
      - echo check kubectl access
     
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker build -t samplerepo .
      - docker tag samplerepo:latest 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com/samplerepo:latest      

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build --cache-from 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com/samplerepo:latest -t samplerepo:latest .
      - docker tag samplerepo:latest 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com/samplerepo:latest 
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com/samplerepo:latest
      - docker pull 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com/samplerepo:latest
      - echo Push the latest image to cluster
      - rm -rf .kube/config
      - aws sts get-caller-identity
      - aws configure set aws_access_key_id "AKIAQLCAGEI6BFJ7YT7U" --profile default && aws configure set aws_secret_access_key "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" --profile default && aws configure set region "ap-northeast-1" --profile default && aws configure set output "" --profile default
      - aws eks update-kubeconfig --name k8scluster --region ap-northeast-1  
      - kubectl apply -f eks_cicd/deployment.yaml
      - kubectl apply -f eks_cicd/service.yaml
#      - kubectl rollout restart -f eks_cicd/deployment.yaml
